services:
  scorvbot:
    build: .
    container_name: scorvbot-container
    links:
      - redis:${REDIS_HOST_NAME:-db}
    volumes:
      - ./${LOG_FOLDER:-logs}/:/scorvbot/${LOG_FOLDER:-logs}
    env_file:
      - .env
    working_dir: /scorvbot
    restart: always
  redis:
    image: redis:7.4-alpine
    container_name: scorvbot-redis-container
    command: redis-server /usr/local/etc/redis/redis.conf --port ${REDIS_HOST_PORT:-6379}
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/:/data
    restart: always
